require ('tsh/telescope')
require ('tsh/autopairs')
require ('tsh/comment')
require ('tsh/treesitter')
require ('tsh/gitsigns')
require ('tsh/bufferline')
require ('tsh/indent_blankline')
--require ('tsh/which_key')
